### ISSUE TITLE
3.0.1 -> 3.1.0 ContractResolverForDataProperty changes the default JSON behavior

### ISSUE THREAD

**Issue by newtonion** [jsreport/jsreport-dotnet-client#1]
Hello,

Prior to the 3.1.0 update the default behavior when generating a report seems to be the same as using a CamelCasePropertyNamesContractResolver. With this latest change, by default, whatever casing is using on the object being passed in is used.

Suggest using the CamelCasePropertyNamesContractResolver by default to maintain 3.0.1 behavior.

**Comment by pofider** [comment]
This was intentional and thoughtful.
I don't see any reason why we should change the casing of the user's properties on the input data.
The original behavior was rather a bug. In the latest we don't change casing, if someone wants this, there is the `ReportingService.ContractResolverForDataProperty` you can use to change it.
